version: "3.7"

services:
  # apache activemq-artemis
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.19
    container_name: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      - AMQ_USER=artemis
      - AMQ_PASSWORD=artemis
      - AMQ_EXTRA_ARGS=--nio --relax-jolokia

  sender:
    profiles:
      - services
    build:
      context: ../sender
      dockerfile: ../containerfiles/Containerfile.temurin
    container_name: sender
    tmpfs:
      - /deployment/ObjectStore
    ports:
      - "8080:8080"
    env_file: services/sender/.env
    deploy:
      resources:
        limits:
          memory: 80m
        reservations:
          memory: 100m
    depends_on:
      - artemis
  receiver:
    profiles:
      - services
    build:
      context: ../receiver
      dockerfile: ../containerfiles/Containerfile.temurin
    container_name: receiver
    tmpfs:
      - /deployment/ObjectStore
    ports:
      - "8081:8080"
    env_file: services/receiver/.env
    deploy:
      resources:
        limits:
          memory: 80m
        reservations:
          memory: 100m
    depends_on:
      - artemis

  native-sender:
    profiles:
      - native-services
    build:
      context: ../sender
      dockerfile: ../containerfiles/Containerfile.distroless-native
    container_name: sender
    tmpfs:
      - /deployment/ObjectStore
    ports:
      - "8080:8080"
    env_file: services/sender/.env
    deploy:
      resources:
        limits:
          memory: 80m
        reservations:
          memory: 100m
    depends_on:
      - artemis
  native-receiver:
    profiles:
      - native-services
    build:
      context: ../receiver
      dockerfile: ../containerfiles/Containerfile.distroless-native
    container_name: receiver
    tmpfs:
      - /deployment/ObjectStore
    ports:
      - "8081:8080"
    env_file: services/receiver/.env
    deploy:
      resources:
        limits:
          memory: 80m
        reservations:
          memory: 100m
    depends_on:
      - artemis